[project]
name = "aithucchienagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
   "dotenv>=0.9.9",
   "langchain-core>=1.0.0",
   "langchain-openai>=1.0.0",
   "langgraph>=1.0.0",
   "openai>=2.6.0",
]
